In [ ]:
class Connect:
  def __init__(self):
    self.strong_signals = []

  def countOnes(self, matrix):
    count = 0
    visited = [[False for j in range(len(matrix[0]))] for i in range(len(matrix))]
    stack = []
    for i in range(len(matrix)):
      for j in range(len(matrix[0])):
        if (not visited[i][j] and matrix[i][j]==1):
          stack.append(str(i)+','+str(j))
          self.DFS(stack, matrix, visited)
          count += 1
    return count

  def DFS(self, stack, matrix, visited):
    
    while len(stack)!= 0:
      x = stack.pop()
      
      i, j = int(x.split(',')[0]), int(x.split(',')[1])
      if (i < 0 or j < 0 or i >= len(matrix) or j >= len(matrix[0]) or visited[i][j] or matrix[i][j] == 0):
        continue

      visited[i][j] = True
      stack.append(str(i-1)+','+str(j-1))
      stack.append(str(i-1)+','+str(j+1))
      stack.append(str(i+1)+','+str(j-1))
      stack.append(str(i+1)+','+str(j+1))
      stack.append(str(i)+','+str(j-1))
      stack.append(str(i)+','+str(j+1))
      stack.append(str(i-1)+','+str(j))
      stack.append(str(i+1)+','+str(j))
      self.strong_signals.append((i, j))

In [ ]:
from random import randint
import numpy as np
matrix = []
for i in range(5):
  a = []
  for j in range(5):
    a.append(randint(0, 1))
  matrix.append(a)
matrix = np.array(matrix) #the matrix where each element represents strong or weak points
print(matrix)
# matrix = [[1, 1, 0, 0, 0], 
#         [1, 1, 0, 0, 0], 
#         [0, 0, 1, 0, 0], 
#         [0, 0, 0, 1, 1]] 
g = Connect()
count = g.countOnes(matrix)
print(count)
print(g.strong_signals)

[[0 0 0 0 1]
 [1 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [1 0 0 0 1]]
4
[(0, 4), (1, 4), (1, 0), (2, 1), (2, 2), (3, 2), (4, 0), (4, 4)]
